import { Term } from "./glossary";

/**
 * batch9 — モダンWeb開発 実務用語 (100 terms)
 * Next.js / React / TypeScript / API / 状態管理 / UI ライブラリ など、
 * Claude Code で実装を頼むときに「これ何？」となりがちな語を日本語化。
 */
export const batch9: Term[] = [
  // ─── Next.js 15+ ────────────────────────────────────────
  { id: "next-app-router", name: "App Router", englishName: "Next.js App Router", category: "Web・インターネット", description: "Next.js 13以降の新しいルーティング。`app/`ディレクトリのフォルダ構造がそのままURLになり、Server Componentsが既定で動く。旧Pages Routerとは別物。", example: "`app/posts/[id]/page.tsx` を作るだけで `/posts/123` のルートが完成する。" },
  { id: "next-pages-router", name: "Pages Router", englishName: "Pages Router", category: "Web・インターネット", description: "Next.jsの従来型ルーティング。`pages/`ディレクトリ配下で動く。App Routerに比べてクライアント中心で、既存プロジェクトで現役でも新規はApp Routerが推奨。", example: "既存サービスを保守するプロジェクトはPages Router、新規はApp Routerで始めるのが2026年の選び方。" },
  { id: "next-server-component", name: "Server Component", englishName: "React Server Component (RSC)", category: "Web・インターネット", description: "サーバー側で描画され、クライアントにHTMLだけ送るReactコンポーネント。DB直アクセス可、JSバンドルが軽くなる。`useState`など動的フックは使えない。", example: "記事一覧ページをServer ComponentでPrisma呼び出しから直接DBを引けば、API層が不要になる。" },
  { id: "next-client-component", name: "Client Component", englishName: "Client Component", category: "Web・インターネット", description: "ブラウザで動くReactコンポーネント。`\"use client\"` ディレクティブで明示する。`useState`やイベントハンドラが必要ならこれにする。", example: "検索フォームや開閉アコーディオンなど、インタラクションがあるUIはClient Componentに切り分ける。" },
  { id: "next-server-action", name: "Server Action", englishName: "Server Action", category: "Web・インターネット", description: "Next.jsでAPIエンドポイントを作らず、関数をサーバー側で実行できる仕組み。`\"use server\"` を書いた関数をformから直接呼べる。", example: "`async function createPost(data){ 'use server'; … }` を`<form action={createPost}>`で呼ぶだけで投稿APIが完成する。" },
  { id: "next-route-handler", name: "Route Handler", englishName: "Route Handler", category: "Web・インターネット", description: "App Routerでの新REST APIの書き方。`app/api/x/route.ts` に `GET/POST/…` 関数をexportする。従来の `pages/api` の後継。", example: "`export async function GET() { return Response.json({ ok: true }) }` だけで `/api/x` のGETハンドラになる。" },
  { id: "next-middleware", name: "Middleware", englishName: "Next.js Middleware", category: "Web・インターネット", description: "リクエストがページに届く前に介入できる処理層。認証チェック、リダイレクト、A/Bテストの振り分けなどに使う。Edge Runtimeで動く。", example: "`middleware.ts` で未ログインユーザーを `/login` にリダイレクトする1行を書けば、全保護ルートに効く。" },
  { id: "next-metadata", name: "Metadata", englishName: "Next.js Metadata", category: "Web・インターネット", description: "Next.js App RouterでOGP・title・descriptionなどSEOタグを型付きで設定する仕組み。`layout.tsx`か`page.tsx`で`export const metadata = {…}`。", example: "`metadata: { openGraph: { images: ['/og.png'] } }` だけで、Xで共有されたときのOG画像が切り替わる。" },
  { id: "next-static-params", name: "generateStaticParams", englishName: "generateStaticParams", category: "Web・インターネット", description: "App Routerで動的ルート（`[slug]`）の静的生成対象を一覧で返す関数。ビルド時に全ページを事前生成してCDNに乗せられる。", example: "ブログ記事一覧を`generateStaticParams`で返せば、全記事ページが静的HTMLとして吐かれて爆速配信される。" },
  { id: "ssg", name: "SSG", englishName: "Static Site Generation", category: "Web・インターネット", description: "ビルド時にHTMLを生成してCDNに置く方式。表示が最速でサーバー負荷もゼロ。更新頻度が低いコンテンツ（ブログ・ドキュメント）に最適。", example: "Next.jsの `output: export` や `generateStaticParams` で、ブログ全記事を静的ページ化する。" },
  { id: "ssr", name: "SSR", englishName: "Server-Side Rendering", category: "Web・インターネット", description: "リクエストごとにサーバーでHTMLを生成する方式。最新データで返せるがCDNキャッシュは効きにくい。ログイン後のダッシュボードなどに向く。", example: "ユーザーごとに違うダッシュボードはSSRで都度描画し、公開ブログはSSGにする使い分け。" },
  { id: "isr", name: "ISR", englishName: "Incremental Static Regeneration", category: "Web・インターネット", description: "SSGの応用で、指定時間ごとに裏で再生成して差分だけ更新する方式。最新性と速度を両立。Next.jsの看板機能。", example: "ECサイトの商品ページを `revalidate: 60` にしておくと、1分ごとに裏でHTMLが再生成され在庫が更新される。" },
  { id: "next-streaming", name: "ストリーミングSSR", englishName: "Streaming SSR", category: "Web・インターネット", description: "HTMLを一部完成したものから順に送る描画。遅い部分を待たずにファーストビューを表示でき、体感速度が劇的に上がる。", example: "記事本文は先に出し、下のコメント欄は後から流し込むストリーミング構成で、LCPが50%改善する。" },
  { id: "next-suspense", name: "Suspense", englishName: "React Suspense", category: "Web・インターネット", description: "非同期データ取得中のUIを「待機中」として宣言的に表現するReactの仕組み。Server ComponentsとのペアでローディングUIをスマートに書ける。", example: "`<Suspense fallback={<Skeleton />}><UserList /></Suspense>` で、ユーザー一覧取得中のスケルトンが自動表示される。" },
  { id: "turbopack", name: "Turbopack", englishName: "Turbopack", category: "Web・インターネット", description: "Vercel製のRust実装ビルドツール。webpack後継でNext.js 15以降の既定ビルダー。大規模アプリでHMRが桁違いに速い。", example: "10万行のNext.jsプロジェクトで、webpackなら2秒かかった再起動がTurbopackなら0.2秒で済む。" },
  { id: "edge-runtime", name: "Edge Runtime", englishName: "Edge Runtime", category: "Web・インターネット", description: "Node.jsより軽量な、CDNエッジで動く実行環境。Next.js Middlewareやサーバーコンポーネントを世界中のPOPで走らせられる。一部Node APIは使えない。", example: "認証チェック処理をEdge Runtimeで動かせば、アジアのユーザーも欧米ユーザーも同じ低レイテンシでログイン体験ができる。" },
  { id: "node-runtime", name: "Node.jsランタイム", englishName: "Node.js Runtime", category: "Web・インターネット", description: "従来のサーバーサイドJS実行環境。ファイルシステム・Native Moduleなどフル機能が使える。Next.jsのサーバー関数の多くはNode.jsで動く。", example: "PDF生成やimage-magickのようなネイティブ依存ライブラリを使う処理は、Edgeではなくnode-runtimeを指定する。" },

  // ─── React 19 ────────────────────────────────────────────
  { id: "react-use-hook", name: "useフック（use()）", englishName: "React use() Hook", category: "Web・インターネット", description: "React 19で追加された汎用フック。Promise・Context・非同期リソースを `use(promise)` のように読み取れる。条件付きで使えるのが新しい。", example: "`const data = use(fetchData())` とServer Componentで書くだけで、データ取得の結果を同期的に扱える。" },
  { id: "react-use-state", name: "useState", englishName: "useState", category: "Web・インターネット", description: "Reactで最も基本の状態管理フック。コンポーネント内の変数を持ち、変化するとUIが自動で再描画される。カウンターやフォーム入力の基礎。", example: "`const [count, setCount] = useState(0)` で、ボタン押下でcountを増やすカウンターが作れる。" },
  { id: "react-use-effect", name: "useEffect", englishName: "useEffect", category: "Web・インターネット", description: "レンダー後に副作用（データ取得・DOM操作・購読）を走らせるフック。React 19以降、外部システム同期用途に限定し、`useSyncExternalStore`の併用が推奨。", example: "`useEffect(() => { fetchData() }, [])` で初回マウント時にデータ取得する典型。" },
  { id: "react-use-memo", name: "useMemo", englishName: "useMemo", category: "Web・インターネット", description: "重い計算結果をキャッシュするフック。依存配列が変わらない限り再計算しない。早すぎる最適化には注意、測ってから使う。", example: "1万件の配列ソート結果を`useMemo`で保持すれば、親の再描画ごとにソートが走らなくなる。" },
  { id: "react-use-ref", name: "useRef", englishName: "useRef", category: "Web・インターネット", description: "DOMへの参照や、再描画不要な可変値を保持するフック。`.current` で読み書き。フォーカス制御、タイマーIDの保持などで使う。", example: "`inputRef.current.focus()` で、ボタンを押したらテキスト欄にフォーカスを飛ばせる。" },
  { id: "react-use-callback", name: "useCallback", englishName: "useCallback", category: "Web・インターネット", description: "関数をメモ化するフック。子コンポーネントに関数を渡す際、毎回新しい関数だと不要な再描画が発生するのを防ぐ。", example: "`useCallback(()=>doSomething(id),[id])` で、同じidなら関数参照を使い回せる。" },
  { id: "react-use-sync-external", name: "useSyncExternalStore", englishName: "useSyncExternalStore", category: "Web・インターネット", description: "外部のストア（ブラウザAPI、Zustand等）から同期的に値を読むReactフック。useEffect+setState で起きる描画のちらつきを避けられる。", example: "ダークモードのclass属性を読むなら、useEffect+useStateではなく useSyncExternalStoreが正解。" },
  { id: "react-server-actions", name: "\"use server\"", englishName: "use server directive", category: "Web・インターネット", description: "Next.js Server Actionsで、この関数がサーバー側でだけ実行される、と明示するディレクティブ。フォーム送信先に関数を直接指定できる。", example: "`'use server'` 付きの関数は内部的にRPCとしてクライアントから呼ばれ、認証などもサーバー側で安全に処理できる。" },
  { id: "react-use-client", name: "\"use client\"", englishName: "use client directive", category: "Web・インターネット", description: "ファイルの先頭に書くと、そのコンポーネントツリー以下をClient Componentにするディレクティブ。状態やイベントハンドラを使うときに必須。", example: "ボタンのonClickを書く小コンポーネントには `\"use client\"` を先頭に書く必要がある。" },
  { id: "react-hydration", name: "ハイドレーション", englishName: "Hydration", category: "Web・インターネット", description: "SSR/SSGで返された静的HTMLに、クライアントのJSがインタラクティブ性を「注入」する工程。SSRの肝で、ここでサーバーとクライアントの描画が一致する必要がある。", example: "SSRとClientで違う値を描くとhydration mismatchエラーになるので、`suppressHydrationWarning` で対処することもある。" },
  { id: "react-concurrent", name: "Concurrent Rendering", englishName: "Concurrent Rendering", category: "Web・インターネット", description: "Reactが描画を中断・再開・優先度付けして行える新モード。`useTransition` や `useDeferredValue` が使える。UIの応答性が上がる。", example: "重い検索結果フィルタを `startTransition` で囲むと、タイプ入力中もUIが固まらない。" },
  { id: "react-portal", name: "Portal", englishName: "React Portal", category: "Web・インターネット", description: "コンポーネントのツリー構造と違う場所（例：`<body>`直下）にDOMを描画する機能。モーダルやツールチップのオーバーレイで使う。", example: "`createPortal(<Modal/>, document.body)` で、ページ構造に関係なくモーダルをbody直下に描画できる。" },
  { id: "react-error-boundary", name: "Error Boundary", englishName: "Error Boundary", category: "Web・インターネット", description: "子コンポーネントで起きたReactエラーを捕まえ、代替UIを表示する仕組み。APIエラーやnull参照で画面全体が白くなるのを防ぐ。", example: "`error.tsx` をApp Routerで作れば、ページ内でthrowされたエラーを自動でError Boundaryが捕捉する。" },
  { id: "react-context", name: "Context API", englishName: "React Context API", category: "Web・インターネット", description: "propsバケツリレーを避けて、深いツリーに値を渡す仕組み。認証情報・テーマ・i18nなどグローバル値で使う。", example: "`AuthContext.Provider` でユーザー情報を包めば、孫以下のコンポーネントが全員`useContext(AuthContext)`で取れる。" },

  // ─── TypeScript 応用 ────────────────────────────────────
  { id: "ts-generic", name: "ジェネリクス", englishName: "Generics", category: "プログラミング", description: "「あとから型を差し込める」関数・型を書く機能。`Array<T>`の`T`がそれ。汎用ユーティリティで型安全性を保ちつつ再利用できる。", example: "`function identity<T>(v: T): T { return v }` は、呼び出し時に型が決まる汎用関数。" },
  { id: "ts-utility-type", name: "ユーティリティ型", englishName: "Utility Types", category: "プログラミング", description: "`Partial<T>`、`Pick<T,K>`、`Omit<T,K>`、`Record<K,V>`など、既存型を変換する組み込み型。ボイラープレートが激減する。", example: "`Omit<User, 'password'>` で、パスワードを抜いたユーザー型をワンライナーで作れる。" },
  { id: "ts-conditional-type", name: "条件型", englishName: "Conditional Types", category: "プログラミング", description: "`T extends U ? A : B` で型レベルのif文を書く機能。入力型に応じて型を切り替える高度ライブラリで多用される。", example: "`type IsArray<T> = T extends any[] ? true : false` のように、型からtrue/falseを派生できる。" },
  { id: "ts-mapped-type", name: "マップ型", englishName: "Mapped Types", category: "プログラミング", description: "`{ [K in keyof T]: 変換 }` で既存型の全キーを一括変換する型定義。`Readonly`や`Partial`の実装がまさにこれ。", example: "`type Nullable<T> = { [K in keyof T]: T[K] | null }` で、全プロパティをnull許容にした型が作れる。" },
  { id: "ts-template-literal", name: "テンプレートリテラル型", englishName: "Template Literal Types", category: "プログラミング", description: "`\`on${Capitalize<E>}\`` のような文字列型の組み合わせ機能。`onClick`、`onChange`のようなイベント名の型を自動生成できる。", example: "`type Event = \`on${'Click'|'Change'}\`` は `'onClick' | 'onChange'`になる。" },
  { id: "ts-infer", name: "infer", englishName: "infer keyword", category: "プログラミング", description: "条件型の中で「この部分の型を取り出して変数にする」キーワード。関数の戻り値型取得（`ReturnType<T>`）などで使われる。", example: "`type ReturnType<T> = T extends (...a:any)=>infer R ? R : never` が infer の代表例。" },
  { id: "ts-type-guard", name: "型ガード", englishName: "Type Guard", category: "プログラミング", description: "値の型を実行時に絞り込む関数。戻り値を `x is User` 型の述語にすると、if内で型が確定する。`typeof`や`instanceof`も型ガードの一種。", example: "`function isUser(x: unknown): x is User { return … }` を書くと、if内でxが`User`として使える。" },
  { id: "ts-satisfies", name: "satisfies演算子", englishName: "satisfies operator", category: "プログラミング", description: "「この値は型Xを満たす」とチェックしつつ、リテラルの具体型は保持するTS 4.9の機能。設定オブジェクトなどで重宝する。", example: "`const config = { a: 1 } satisfies Record<string, number>` なら、型はwidenせず`{a: number}`のまま保持。" },
  { id: "ts-enum", name: "TypeScript Enum", englishName: "TypeScript Enum", category: "プログラミング", description: "列挙型。`enum Role { Admin, User }`のように定数の集合を表現。近年は `as const` オブジェクト＋Union型で代替するのが主流。", example: "`export const Role = { Admin: 'admin', User: 'user' } as const` でenumを使わずに同等の表現が可能。" },
  { id: "ts-tsconfig", name: "tsconfig.json", englishName: "tsconfig.json", category: "プログラミング", description: "TypeScriptプロジェクトの設定ファイル。`strict`、`paths`、`target`、`moduleResolution`などコンパイラの挙動を制御する。", example: "`\"strict\": true` を入れるかどうかで、プロジェクトの型安全性が根本から変わる。" },
  { id: "ts-strict-mode", name: "strictモード", englishName: "strict mode", category: "プログラミング", description: "tsconfigの `strict: true` で有効になるチェック群。`strictNullChecks`、`noImplicitAny`などが一括ON。新規プロジェクトでは必須。", example: "strictモードなら `x: string = null` は型エラーになり、nullポインタ系バグの大半を未然に防げる。" },

  // ─── バリデーション・スキーマ ───────────────────────────
  { id: "zod", name: "Zod", englishName: "Zod", category: "プログラミング", description: "TypeScript向けのスキーマ定義・バリデーションライブラリ。`z.object({ email: z.string().email() })` のように書き、型とランタイム検証を同時に得られる。", example: "Server Actionsで `z.object(…)` を使えば、フォーム入力の検証と型付けが1本で終わる。" },
  { id: "yup", name: "Yup", englishName: "Yup", category: "プログラミング", description: "Zodより古参のスキーマバリデーションライブラリ。React Hook Formと組み合わせて使われることが多い。Zodに比べると型推論はやや弱い。", example: "既存のReact Hook FormプロジェクトではYupが使われていることが多く、新規ならZodが主流。" },
  { id: "valibot", name: "Valibot", englishName: "Valibot", category: "プログラミング", description: "Zodよりバンドルが軽量で、モジュール方式で必要分だけimportできる次世代バリデーションライブラリ。大規模SaaSで採用が増えている。", example: "モバイルで軽量化が必要なPWAでは、Zodの代わりにValibotでバンドル50KB削減する事例がある。" },
  { id: "json-schema", name: "JSON Schema", englishName: "JSON Schema", category: "プログラミング", description: "JSON構造のバリデーション仕様。OpenAPI・ajvなど多数のツールが対応し、言語をまたいだスキーマ共有に強い。", example: "OpenAPIで定義したスキーマをJSON Schemaとしてajvに読ませれば、APIリクエストの型検証が自動化できる。" },
  { id: "openapi", name: "OpenAPI", englishName: "OpenAPI Specification", category: "プログラミング", description: "REST APIの仕様をYAML/JSONで書く標準フォーマット。旧Swagger。コード生成・ドキュメント・テストまで派生ツールが揃う。", example: "OpenAPI定義から`openapi-typescript-codegen`で型付きクライアントを自動生成し、フロントとバックの型ズレを防ぐ。" },

  // ─── データ取得・状態管理 ───────────────────────────────
  { id: "tanstack-query", name: "TanStack Query", englishName: "TanStack Query (React Query)", category: "Web・インターネット", description: "サーバーからのデータ取得・キャッシュ・再取得を宣言的に扱えるライブラリ。ローディング・エラー・再試行の定型コードが激減する。", example: "`useQuery({ queryKey: ['posts'], queryFn: fetchPosts })` だけで、キャッシュ付きのデータ取得が完成。" },
  { id: "swr", name: "SWR", englishName: "SWR", category: "Web・インターネット", description: "VercelがOSSで出すデータ取得フック。「古いデータを先に表示しつつ裏で再取得」の戦略（stale-while-revalidate）が名前の由来。", example: "`useSWR('/api/me', fetcher)` とだけ書けば、ユーザー情報をキャッシュ＋自動再検証で扱える。" },
  { id: "zustand", name: "Zustand", englishName: "Zustand", category: "Web・インターネット", description: "React向けの軽量状態管理ライブラリ。Reduxより記述量が圧倒的に少なく、`create(set => …)` だけでグローバルストアが組める。", example: "Reduxで100行書く機能が、Zustandなら10行で書けてしまう。中小規模SPAで主流。" },
  { id: "jotai", name: "Jotai", englishName: "Jotai", category: "Web・インターネット", description: "「原子（atom）」単位で状態を管理するReactライブラリ。必要なatomだけをサブスクライブするので再描画が最小に抑えられる。", example: "フィルタ条件を複数atomで分離すると、それぞれ独立に更新でき関係ない部分が再描画されない。" },
  { id: "redux-toolkit", name: "Redux Toolkit", englishName: "Redux Toolkit (RTK)", category: "Web・インターネット", description: "Reduxの公式推奨セット。ボイラープレート激減、イミュータビリティもimmerで自動化。大規模アプリでの状態管理の定番。", example: "RTK QueryはTanStack Query相当の機能をReduxの枠組みで提供し、`createSlice`と組み合わせて使う。" },
  { id: "signals", name: "Signals", englishName: "Signals", category: "Web・インターネット", description: "値の変化を自動で追跡する、細粒度のリアクティブ原始型。Solid/Preact/Vueで採用。Reactにも実験導入が進む。", example: "`const count = signal(0)` で、count.valueを使うコンポーネントだけが再描画される。" },

  // ─── フォーム・UI ───────────────────────────────────────
  { id: "react-hook-form", name: "React Hook Form", englishName: "React Hook Form", category: "Web・インターネット", description: "Reactフォーム管理ライブラリの定番。再描画を抑えたパフォーマンスと、ZodなどのバリデーションResolverで型安全性を両立。", example: "`useForm({ resolver: zodResolver(schema) })` で、型推論・バリデーション・エラー表示が一気に揃う。" },
  { id: "formik", name: "Formik", englishName: "Formik", category: "Web・インターネット", description: "Reactフォームの老舗ライブラリ。親しみやすいAPIが人気だが、近年はReact Hook Formに主役を譲りつつある。", example: "既存の大規模SaaSにはFormikが残っていることが多く、漸次React Hook Formへ移行するプロジェクトが増加中。" },
  { id: "shadcn-ui", name: "shadcn/ui", englishName: "shadcn/ui", category: "Web・インターネット", description: "Radix UI + Tailwind CSSをベースにした「コピペ式」コンポーネント集。npmインストールではなくCLIでファイルを自分のリポに入れる設計。", example: "`npx shadcn add button` でボタンコンポーネントが自分のコードとして入り、自由にカスタマイズできる。" },
  { id: "radix-ui", name: "Radix UI", englishName: "Radix UI", category: "Web・インターネット", description: "アクセシビリティを徹底したReact向けヘッドレスUIライブラリ。見た目はないがキーボード操作・スクリーンリーダー対応が全て実装済み。shadcn/uiの土台。", example: "RadixのDialogを使えば、ESCキー対応・フォーカスロックなど面倒な部分が全部自動で整う。" },
  { id: "headless-ui", name: "Headless UI", englishName: "Headless UI", category: "Web・インターネット", description: "Tailwind Labs提供のヘッドレスUIライブラリ。Radixに似て「ロジックだけを提供し、見た目は自分で書く」発想。", example: "Menu・Dialog・Comboboxなど定番UIがHeadless UIでロジック部分を借りて、見た目はTailwindで自作できる。" },
  { id: "framer-motion", name: "Framer Motion", englishName: "Framer Motion", category: "Web・インターネット", description: "Reactでアニメーションを宣言的に書ける人気ライブラリ。`<motion.div animate={{ x: 100 }} />` のようにシンプルに書ける。", example: "モーダルの開閉、スワイプジェスチャー、ページ遷移アニメーションまでFramer Motionで数行で実装できる。" },
  { id: "tailwind-css", name: "Tailwind CSS", englishName: "Tailwind CSS", category: "Web・インターネット", description: "ユーティリティクラス（`p-4`, `text-center`等）でスタイリングするCSSフレームワーク。ファイル跨ぎのCSS命名地獄を回避でき、JITビルドで不要クラスを削除。", example: "Next.jsプロジェクトで `className=\"bg-white p-4 rounded-lg\"` と書くだけでカードUIが完成する。" },
  { id: "tailwind-v4", name: "Tailwind CSS v4", englishName: "Tailwind CSS v4", category: "Web・インターネット", description: "Tailwind CSSのメジャーアップデート。Rust製の新エンジンで高速化、`@import \"tailwindcss\"` のみで動くなど設定が劇的に簡素化された。", example: "v4では`tailwind.config.ts`を書かず、CSS内で`@theme`を使って色やサイズを定義するのが新しい流儀。" },
  { id: "css-modules", name: "CSS Modules", englishName: "CSS Modules", category: "Web・インターネット", description: "ファイルごとにスコープされたCSSを書ける仕組み。クラス名がハッシュ化され他ファイルと衝突しない。Next.jsでも標準対応。", example: "`Button.module.css` の`.primary`は他のCSSと絶対衝突しないため、大規模SPAでも命名事故が起きない。" },
  { id: "css-in-js", name: "CSS-in-JS", englishName: "CSS-in-JS", category: "Web・インターネット", description: "JSでCSSを書くアプローチの総称。styled-components、Emotionが代表。動的なスタイルに強いが、Server Components時代はTailwindに押され気味。", example: "2026年時点では、CSS-in-JSよりTailwind + CSS Modulesの組み合わせが新規プロジェクトで主流。" },

  // ─── API・通信 ──────────────────────────────────────────
  { id: "trpc", name: "tRPC", englishName: "tRPC", category: "プログラミング", description: "TypeScriptで型安全なフルスタックAPIを作る仕組み。OpenAPIやgRPCを書かず、関数呼び出しと同じ感覚でクライアントが呼べる。", example: "サーバー関数の型がそのままクライアントに伝わるので、APIの型ずれによるバグがゼロになる。" },
  { id: "grpc", name: "gRPC", englishName: "gRPC", category: "プログラミング", description: "Googleが開発した高速なRPCフレームワーク。Protocol Buffersでスキーマ定義し、HTTP/2で通信。マイクロサービス間通信に多用。", example: "社内マイクロサービス間の通信をgRPCにすると、RESTより数倍高速でペイロードも軽量になる。" },
  { id: "protobuf", name: "Protocol Buffers", englishName: "Protocol Buffers", category: "プログラミング", description: "Googleの軽量・高速なシリアライズ形式。`.proto`ファイルで型を定義すると、多言語でコード生成できる。gRPCの標準データ形式。", example: "JSONより小さく速いので、モバイル・IoT・高頻度通信の場面でProtobufが選ばれる。" },
  { id: "websocket", name: "WebSocket", englishName: "WebSocket", category: "Web・インターネット", description: "ブラウザとサーバー間で双方向の常時接続を維持できる通信プロトコル。チャット・ライブ更新・オンラインゲームの定番。", example: "Supabase RealtimeやChatGPTのストリーミングUIはWebSocketベースで実装されている。" },
  { id: "sse", name: "Server-Sent Events", englishName: "Server-Sent Events (SSE)", category: "Web・インターネット", description: "サーバーからクライアントへの一方向ストリーム。WebSocketより軽量で、LLMの応答ストリーミングに多用される。", example: "ClaudeやChatGPTの文字が順次現れる表示はSSEで実装されていることが多い。" },
  { id: "polling", name: "ポーリング", englishName: "Polling", category: "Web・インターネット", description: "クライアントが一定間隔でサーバーに問い合わせて更新を確認する方式。実装が簡単だが無駄なリクエストが多い。", example: "軽微なデータ更新にはポーリング、高頻度ならWebSocketを使い分ける。" },
  { id: "long-polling", name: "ロングポーリング", englishName: "Long Polling", category: "Web・インターネット", description: "サーバーが新情報を持つまでレスポンスを返さない擬似リアルタイム方式。WebSocket登場前の代替手段。現在は少数派。", example: "WebSocketを使えない古いブラウザ向けに、ロングポーリングをフォールバックとして残す構成がある。" },
  { id: "webhook-delivery", name: "Webhook配信", englishName: "Webhook Delivery", category: "プログラミング", description: "外部サービスが、イベント発生時にこちらのURLへPOSTしてくる仕組み。Stripeの決済通知、GitHubのpushイベントが代表。", example: "Stripeの`payment_succeeded` Webhookを受けたら、DBの注文ステータスを自動で更新する。" },

  // ─── 認証・セッション ──────────────────────────────────
  { id: "oidc", name: "OIDC", englishName: "OpenID Connect", category: "データ・セキュリティ", description: "OAuth 2.0の上に作られた認証プロトコル。「誰がログインしたか」をIDトークンで返す。Google/Azure/Auth0のSSOで実質標準。", example: "`Sign in with Google` の裏で動いているのはOIDC。IDトークン（JWT）にユーザー情報が入る。" },
  { id: "session-cookie", name: "セッションクッキー", englishName: "Session Cookie", category: "データ・セキュリティ", description: "ブラウザに保存される短命な認証情報。サーバー側のセッションIDを入れておくのが伝統的、最近はJWTも多い。", example: "HttpOnly Secure SameSite=Lax の組み合わせが、XSS・CSRF耐性を高めるセッションクッキーの標準。" },
  { id: "refresh-token", name: "リフレッシュトークン", englishName: "Refresh Token", category: "データ・セキュリティ", description: "アクセストークンが切れたときに、再ログインせず新しいトークンを取る用の長寿命トークン。厳重に保管される。", example: "Supabase Authは自動でリフレッシュトークンを使って無期限ログインを維持してくれる。" },
  { id: "access-token", name: "アクセストークン", englishName: "Access Token", category: "データ・セキュリティ", description: "APIアクセス用の短命トークン。JWTやopaqueな文字列として、ヘッダー`Authorization: Bearer …` で送る。", example: "`fetch('/api', { headers: { Authorization: 'Bearer ' + token } })` でアクセストークンを使うのが定石。" },
  { id: "csrf-token", name: "CSRFトークン", englishName: "CSRF Token", category: "データ・セキュリティ", description: "CSRF攻撃を防ぐため、フォームに埋め込む秘密文字列。サーバーが受け取ったトークンと突合して改ざん検知する。", example: "SameSite=Laxクッキー＋CSRFトークンの二重対策で、他サイトから埋め込まれた`<form>`からの不正投稿を防げる。" },
  { id: "magic-link", name: "マジックリンク", englishName: "Magic Link", category: "データ・セキュリティ", description: "メール送信のリンクをクリックするだけでログインできる方式。パスワード不要で、フィッシング耐性や運用の簡便さで人気。", example: "Supabase Authのマジックリンクを使えば、パスワード管理からUIまで10行で実装できる。" },
  { id: "passkey", name: "パスキー", englishName: "Passkey", category: "データ・セキュリティ", description: "パスワードの代わりに「デバイス内の秘密鍵」で認証する次世代仕組み（WebAuthnベース）。Face ID/指紋で署名してログイン。", example: "GitHub・Google・AppleなどがPasskeyに対応し、「パスワードを入れない未来」が現実になっている。" },
  { id: "mfa", name: "多要素認証（MFA）", englishName: "Multi-Factor Authentication", category: "データ・セキュリティ", description: "パスワード＋ワンタイムコードなど、2つ以上の要素で認証する仕組み。アカウント乗っ取り対策の必須機能。", example: "SupabaseでもTOTP（Google Authenticator型）のMFAがAuth設定から簡単に有効化できる。" },

  // ─── TypeScript周辺ツール ───────────────────────────────
  { id: "eslint", name: "ESLint", englishName: "ESLint", category: "プログラミング", description: "JavaScript/TypeScriptの静的解析ツール。未使用変数・危険な書き方・フォーマット違反を検出。プロジェクトの品質を底上げ。", example: "`eslint .` でバグの芽を検出、`--fix`で自動修正までやってくれる。" },
  { id: "prettier", name: "Prettier", englishName: "Prettier", category: "プログラミング", description: "「意見の強い」自動フォーマッタ。インデント・改行・クォートの一貫性を強制し、コードレビューの「スタイル論争」をなくす。", example: "保存時にPrettierが走るエディタ設定にすれば、チーム全員の書きぶりが自動で揃う。" },
  { id: "biome", name: "Biome", englishName: "Biome", category: "プログラミング", description: "ESLint + Prettier相当のチェック・整形を一つにしたRust製高速ツール。設定ファイル1つで済み、速度が桁違い。", example: "モノレポでESLintが30秒かかっていた処理が、Biomeに置き換えたら2秒になる例も多い。" },
  { id: "vitest", name: "Vitest", englishName: "Vitest", category: "プログラミング", description: "Vite製の高速テスティングフレームワーク。Jest互換APIで、ESM・TS・JSXをそのまま扱える。近年の新規プロジェクトで第一選択。", example: "`vitest` と打つだけで、型付きテストがウォッチモードで走る。CIでもJestより大幅に速い。" },
  { id: "playwright", name: "Playwright", englishName: "Playwright", category: "プログラミング", description: "Microsoftが開発するE2Eテストツール。Chromium/Firefox/WebKitを横断でき、Trace Viewerで失敗時のリプレイが見られる。", example: "`page.locator('text=ログイン').click()` のような直感的API で、実ブラウザ操作のテストが書ける。" },
  { id: "storybook", name: "Storybook", englishName: "Storybook", category: "Web・インターネット", description: "UIコンポーネントを独立した環境でカタログ化するツール。状態ごとに画面を並べ、デザイナーとエンジニアの共通言語になる。", example: "ボタンのhover/disabled/loadingなど全状態をStorybookに並べれば、デザインレビューが高速化する。" },
  { id: "msw", name: "MSW", englishName: "Mock Service Worker", category: "プログラミング", description: "Service Workerでネットワークレイヤーをモックするライブラリ。テスト・開発中にバックエンドがなくてもフロントが動かせる。", example: "Storybook + MSWで、ネット接続なしでもAPIレスポンスを模して全画面を再現できる。" },
];
