import { Term } from "./glossary";

/**
 * batch8 — Claude Code / Cowork / MCP / エージェント実務 (100 terms)
 * Claude Code や Claude Cowork をいざ触ったとき、ドキュメントや記事に出てきて
 * 「これ何だっけ…」となりがちな用語を徹底的に日本語化。
 */
export const batch8: Term[] = [
  // ─── Claude Code 基礎 ──────────────────────────────────────
  { id: "cc-cli", name: "Claude Code CLI", englishName: "Claude Code CLI", category: "Claude・ChatGPT", description: "AnthropicのAIプログラミングエージェントをターミナルから使うコマンドラインツール。`claude` と打てば会話を始められ、ファイル読み書きやコマンド実行までAIが自走する。", example: "リポジトリのルートで `claude` と打ち、「このバグを直して」と頼むだけでClaude Codeが差分まで出してくる。" },
  { id: "cc-agent-sdk", name: "Claude Agent SDK", englishName: "Claude Agent SDK", category: "Claude・ChatGPT", description: "Claude Codeと同じ仕組みで「独自のAIエージェント」を作れる開発キット。Python/TypeScriptから呼び出し、ツール使用・ファイル操作・サブエージェントなどが全部使える。", example: "社内のヘルプデスクBotをClaude Agent SDKで作れば、Zendeskを読みながら返答するエージェントが数百行で構築できる。" },
  { id: "cc-subagent", name: "サブエージェント", englishName: "Subagent", category: "Claude・ChatGPT", description: "メインのClaude Codeから呼び出される「専門担当のAI」。レビュー・設計・探索など役割別に分かれ、メインの文脈を汚さずに並列で働ける。エージェントの部下のイメージ。", example: "「フロントエンドエンジニア」「セキュリティレビュアー」など役割別のサブエージェントを組み合わせ、1人の開発チームをAIで再現。" },
  { id: "cc-skill", name: "Skill（スキル）", englishName: "Skill", category: "Claude・ChatGPT", description: "Claude Codeに「特定の作業手順」を覚えさせる仕組み。マークダウンで手順書を書いておくと、関連する依頼のときだけ自動で呼び出される。重たい説明文を常時ロードせずに済む。", example: "「PR作成時にこのテンプレで書く」というSkillを登録しておけば、毎回プロンプトで指示しなくても同じ品質のPR文ができる。" },
  { id: "cc-hook", name: "Hook（フック）", englishName: "Hook", category: "Claude・ChatGPT", description: "Claude Codeのイベント（ツール実行前後・停止・プロンプト送信時など）に自動で割り込むシェルコマンド。「毎回保存前にフォーマッタを走らせる」などを強制できる。", example: "`PostToolUse` フックに `prettier --write` を入れれば、ClaudeがファイルをEdit/Writeするたびに自動整形される。" },
  { id: "cc-slash-command", name: "スラッシュコマンド", englishName: "Slash Command", category: "Claude・ChatGPT", description: "Claude Codeで `/review` のように打てる独自コマンド。マークダウンで実装を書いておくと、頻繁に使う指示を1コマンドで呼べる。", example: "`/ultrareview` を自作しておけば、PRレビューの長文プロンプトを毎回コピペせずに一発で走らせられる。" },
  { id: "cc-output-style", name: "Output Style", englishName: "Output Style", category: "Claude・ChatGPT", description: "Claude Codeの回答スタイルをプロンプトレベルで切り替える設定。「日本語丁寧体」「コードレビューモード」など、デフォルトの応答方針を差し替えられる。", example: "`/output-style japanese-formal` に切り替えれば、以降の応答が敬語ベースの報告調になる。" },
  { id: "cc-statusline", name: "ステータスライン", englishName: "Statusline", category: "Claude・ChatGPT", description: "Claude Code画面下部に常に表示される情報バー。ブランチ名・モデル・残コンテキストなどを自由にカスタマイズできる。", example: "現在のgitブランチと消費トークンを表示するstatuslineを設定すると、コンテキスト圧迫に気づきやすい。" },
  { id: "cc-plan-mode", name: "Plan Mode", englishName: "Plan Mode", category: "Claude・ChatGPT", description: "Claude Codeに「まず計画だけ立てて、コードは書かない」モード。大規模変更の前に方針をレビューさせたいときに使う。`ExitPlanMode` で実行フェーズに抜ける。", example: "DBスキーマ全面改修の前にPlan Modeで設計書を書かせ、合意が取れてから実装に入ると事故が減る。" },
  { id: "cc-permission-mode", name: "Permission Mode", englishName: "Permission Mode", category: "Claude・ChatGPT", description: "Claude Codeがツールを呼び出す際の承認レベル。`default` / `acceptEdits` / `bypassPermissions` などがあり、自動化度と安全性のバランスを決める。", example: "CIで夜間バッチとして走らせるときは `bypassPermissions`、手動作業時は `default` で逐一確認、という使い分け。" },
  { id: "cc-sandbox-mode", name: "Sandbox Mode", englishName: "Sandbox Mode", category: "Claude・ChatGPT", description: "Claude Codeが書き込み可能範囲を制限して動作する安全モード。プロジェクト外への書き込みやネットワーク通信を制限する。", example: "Sandbox Mode有効時、Claudeは `/etc/…` など意図外のパスには書けないため、事故が起きにくい。" },
  { id: "cc-claude-md", name: "CLAUDE.md", englishName: "CLAUDE.md", category: "Claude・ChatGPT", description: "Claude Codeが起動時に必ず読む常駐コンテキストファイル。プロジェクトのルールや技術スタックを書いておくと、毎回同じ指示を繰り返さずに済む。`AGENTS.md`という別名もある。", example: "CLAUDE.mdに「このリポはNext.js 16。APIのテストはfetchMockで書く」と書いておけば、毎回の前提説明が不要に。" },
  { id: "cc-agents-md", name: "AGENTS.md", englishName: "AGENTS.md", category: "Claude・ChatGPT", description: "CLAUDE.mdと同じ役割の、エージェント全般向け常駐ドキュメント。Cursor、Gemini Code、Codexなどとの互換性がある中立名。", example: "社内でCursorとClaude Codeが混在する環境では、ルールをAGENTS.mdに書いて両対応にする。" },
  { id: "cc-memory", name: "オートメモリ", englishName: "Auto Memory", category: "Claude・ChatGPT", description: "Claude Codeが会話をまたいで覚えておくユーザー情報・好み・プロジェクト状況を記録する仕組み。ファイル単位で管理され、MEMORY.mdがインデックスになる。", example: "「この人はTypeScript好きで2スペースインデント派」というフィードバックを自動メモリに残せば、2回目以降の指示が楽になる。" },
  { id: "cc-context-compact", name: "Context Compact", englishName: "Context Compaction", category: "Claude・ChatGPT", description: "会話が長くなりコンテキストが溢れそうなとき、過去のやりとりをAIが要約して圧縮する機能。Claude Codeは自動で発動する。", example: "5時間の長丁場セッションでも、Compactが走るとことでコンテキスト切れを起こさず連続作業が続けられる。" },
  { id: "cc-session", name: "セッション", englishName: "Session", category: "Claude・ChatGPT", description: "Claude Codeの1回の会話単位。`/resume` で過去セッションに戻れる。長丁場の作業はセッションID付きで管理される。", example: "「昨日の続きから」と言えば、Claudeが該当セッションを復元して続きから作業できる。" },
  { id: "cc-todo-write", name: "TodoWrite", englishName: "TodoWrite Tool", category: "Claude・ChatGPT", description: "Claude Codeが長いタスクを分解して進捗を追うための内蔵ToDoツール。画面上に進行中・完了のタスクが可視化される。", example: "リファクタリング3時間作業で、ClaudeがTodoWriteで10項目に分解し、1つずつチェックしていく様子が画面に出る。" },
  { id: "cc-bash-tool", name: "Bashツール", englishName: "Bash Tool", category: "Claude・ChatGPT", description: "Claude Codeに搭載されたシェル実行ツール。`npm test` や `git commit` などを直接実行できる。権限モードで実行可否を制御。", example: "「テスト通るか見て」と言うと、ClaudeがBashツールで `npm test` を流し、結果を読んで修正提案まで出す。" },
  { id: "cc-edit-tool", name: "Editツール", englishName: "Edit Tool", category: "Claude・ChatGPT", description: "Claude Codeの文字列置換ツール。ファイル全体を書き直さず、差分だけを送信するためトークン消費が少なく高速。", example: "大きなファイルの1行だけ直したいときは、Editツールが使われてコンテキストをほとんど消費しない。" },
  { id: "cc-write-tool", name: "Writeツール", englishName: "Write Tool", category: "Claude・ChatGPT", description: "Claude Codeのファイル新規作成・全書き換え用ツール。小さな差分はEdit、丸ごと作るならWriteという使い分けになる。", example: "新しいコンポーネントを0から作るときはWriteツールで一気に書く。" },
  { id: "cc-read-tool", name: "Readツール", englishName: "Read Tool", category: "Claude・ChatGPT", description: "Claude Codeのファイル読み取りツール。行番号付きで返し、行範囲の部分読みにも対応する。大容量ファイルの節約読みに必須。", example: "1万行のログファイルを `Read(offset: 9000, limit: 500)` で後ろの500行だけ読ませるとトークン節約。" },
  { id: "cc-glob-tool", name: "Globツール", englishName: "Glob Tool", category: "Claude・ChatGPT", description: "ファイル名パターンで一致するファイル一覧を高速に返す検索ツール。`src/**/*.tsx` のような書き方で「TSXだけ」を抽出。", example: "`Glob('**/*.test.ts')` で全テストファイルの一覧を取得し、どこにテストが書かれているか把握できる。" },
  { id: "cc-grep-tool", name: "Grepツール", englishName: "Grep Tool", category: "Claude・ChatGPT", description: "Claude Codeの中身検索ツール。ripgrepベースで、正規表現・ファイルタイプ・行番号付与などに対応。爆速のコード検索が可能。", example: "`Grep('useAuth', type: 'ts')` でTS内の `useAuth` 使用箇所を一覧できる。" },
  { id: "cc-webfetch", name: "WebFetch", englishName: "WebFetch", category: "Claude・ChatGPT", description: "Claude CodeがURLを取得してMarkdown化するツール。ドキュメントサイトやブログを読み込んで要約・引用ができる。", example: "「このページの仕様をREADMEに反映して」と言って公式ドキュメントURLを渡すと、WebFetchで取得→本文に反映する。" },
  { id: "cc-websearch", name: "WebSearch", englishName: "WebSearch", category: "Claude・ChatGPT", description: "Claude Codeが最新情報を検索するツール。学習データにない新APIや直近のバグ情報を取ってこられる。", example: "「Next.js 16の新機能を調べて」と頼むと、WebSearchで最新記事を拾って差分を整理してくれる。" },
  { id: "cc-task-tool", name: "Agentツール（Task）", englishName: "Agent / Task Tool", category: "Claude・ChatGPT", description: "Claude Codeからサブエージェントを起動する内部ツール。並列・バックグラウンド動作もでき、大規模探索や並行レビューを実現する。", example: "調査を3つのサブエージェントに並列で投げ、戻ってきた結果をメインエージェントが統合するワークフロー。" },
  { id: "cc-run-in-background", name: "バックグラウンドタスク", englishName: "Run in Background", category: "Claude・ChatGPT", description: "Claude Codeでdev serverやビルドをバックグラウンド起動する仕組み。ログはモニターできる。並行作業に必須。", example: "`npm run dev` を `run_in_background: true` で起動し、別ツール呼び出しでログを確認しながら作業する。" },
  { id: "cc-monitor-tool", name: "Monitor", englishName: "Monitor Tool", category: "Claude・ChatGPT", description: "バックグラウンドで走るコマンドのログを追いかけるツール。until条件で待機し、完了したら通知を受け取れる。", example: "ビルドが終わるのを Monitor で待ち、成功したら次のテストに進むパイプラインをAI任せに組める。" },
  { id: "cc-schedule-wakeup", name: "ScheduleWakeup", englishName: "ScheduleWakeup", category: "Claude・ChatGPT", description: "Claude Codeが「N秒後にもう一度起きて作業を続ける」ための内部ツール。デプロイ完了待ちなど長時間の非同期タスクで使う。", example: "Vercelビルド完了を待つ際、ScheduleWakeupで90秒後に自分を起こして再確認する動きができる。" },

  // ─── MCP ───────────────────────────────────────────────────
  { id: "mcp-server", name: "MCPサーバー", englishName: "MCP Server", category: "プログラミング", description: "Claudeと外部ツールを仲介する小さなプロセス。GitHub・Slack・Supabaseなどの機能を「ツール／リソース」として公開する。USBハブのような存在。", example: "Supabase MCPサーバーを起動すると、Claudeから `mcp__supabase__execute_sql` でDBに直接クエリできる。" },
  { id: "mcp-client", name: "MCPクライアント", englishName: "MCP Client", category: "プログラミング", description: "MCPサーバーに接続してツールを呼び出す側。Claude Code、Claude Desktop、CursorなどがそれぞれMCPクライアントとして振る舞う。", example: "Claude DesktopはMCPクライアントとして、設定に書かれた複数のMCPサーバーに自動接続する。" },
  { id: "mcp-tool", name: "MCPツール", englishName: "MCP Tool", category: "プログラミング", description: "MCPサーバーが公開する個別の機能単位。`search_issues`・`send_message`のような実行可能アクション。Claudeが判断して呼び出す。", example: "GitHubのMCPツール `create_pr` を呼ぶだけで、AIがPRを立てられるようになる。" },
  { id: "mcp-resource", name: "MCPリソース", englishName: "MCP Resource", category: "プログラミング", description: "MCPサーバーが「読める参照データ」として公開するもの。ドキュメントやDBスキーマなど、ツール実行ではなく情報取得用。", example: "DB MCPサーバーが `resource:schema/users` を公開し、ClaudeがRLSを考慮したSQLを書く前に読む。" },
  { id: "mcp-prompt", name: "MCPプロンプト", englishName: "MCP Prompt", category: "プログラミング", description: "MCPサーバーが提供する「使える定型プロンプト」。スラッシュコマンドのように呼び出せ、ツールと組み合わせた標準手順を配布できる。", example: "`/figma.design_review` のようなMCPプロンプトで、Figmaから画面情報を取りレビューを書く手順をワンクリックで走らせる。" },
  { id: "mcp-transport", name: "MCPトランスポート", englishName: "MCP Transport", category: "プログラミング", description: "MCPの通信路の種類。標準入出力（stdio）、HTTP、SSEなどがある。ローカル常駐はstdio、クラウド連携はHTTP/SSEを使う。", example: "Supabase MCPは stdio、Cloudflare Developer MCPは HTTPトランスポートで提供される。" },
  { id: "mcp-config", name: "MCP設定（mcp.json）", englishName: "MCP Config", category: "プログラミング", description: "どのMCPサーバーをどう起動するかを書くJSON設定。`command`、`args`、`env` を並べる。Claude Desktopやclaude.ai設定から編集。", example: "mcp.jsonに`supabase`エントリを足すと、全セッションで自動的にDBツールが使える状態になる。" },
  { id: "mcp-stdio", name: "stdioトランスポート", englishName: "stdio Transport", category: "プログラミング", description: "標準入出力を使うMCP通信方式。ローカルに常駐させ、クライアントが子プロセスとして起動して使う。最も一般的な形。", example: "`npx @supabase/mcp-server --url … --service-role-key …` はstdioで起動するMCPサーバー。" },

  // ─── Claude Cowork / Dispatch ─────────────────────────────
  { id: "cowork-workspace", name: "Workspace", englishName: "Workspace", category: "Claude・ChatGPT", description: "Claude Cowork上のチーム作業単位。メンバーとデータソース（ドキュメント/DB/MCP）をまとめ、共有されたコンテキストでAIが動く場所。", example: "「マーケ部」Workspaceに広告データを繋げば、全員が同じClaudeを通じて分析・報告書作成を共同でできる。" },
  { id: "cowork-data-source", name: "データソース", englishName: "Data Source", category: "Claude・ChatGPT", description: "Claude Coworkに接続された外部データ源。Google Drive、Slack、Supabase、Notion等を接続するとClaudeが横断的に検索・要約できる。", example: "SlackとGoogle Driveを同じデータソースとして繋げば、「先週の議事録とSlackの決定事項」を1本で答えてくれる。" },
  { id: "cowork-dispatch-task", name: "Dispatchタスク", englishName: "Dispatch Task", category: "Claude・ChatGPT", description: "Claude Coworkの並列エージェント機能で走らせる個別の仕事。大量データ処理や分析をAIに複数同時に任せられる。", example: "250店舗の月次レポートをDispatchで並列実行すれば、1件ずつ順番に回すより数倍速く終わる。" },
  { id: "cowork-connector", name: "コネクター", englishName: "Connector", category: "Claude・ChatGPT", description: "Claude Coworkで各種SaaSを繋ぐ公式の接続モジュール。OAuthで認証すれば、MCPを自前で立てなくても基幹ツールと連携できる。", example: "Gmailコネクターを有効にするだけで、受信箱からの要約・返信ドラフト生成がClaudeに任せられるようになる。" },
  { id: "cowork-project-canvas", name: "プロジェクトキャンバス", englishName: "Project Canvas", category: "Claude・ChatGPT", description: "Claude Coworkでテキスト・表・図を並べて共同編集できる作業空間。ArtifactsやGoogleドキュメントに近いが、AIが常駐して書き換えてくれる。", example: "四半期戦略をProject Canvasに書き、Claudeに「競合調査を埋めて」と頼むと、空欄がデータ付きで埋まる。" },

  // ─── Claudeモデル・API ───────────────────────────────────
  { id: "cc-opus-47", name: "Claude Opus 4.7", englishName: "Claude Opus 4.7", category: "Claude・ChatGPT", description: "Anthropicの最上位モデル（2026年時点）。複雑な推論、長時間の自律作業、コード設計に最も強い。高品質な判断が必要な場面で選ぶ。", example: "巨大リファクタや新規アーキテクチャ設計はOpus 4.7でじっくり考えさせ、軽作業はSonnetに回すと費用対効果が良い。" },
  { id: "cc-sonnet-46", name: "Claude Sonnet 4.6", englishName: "Claude Sonnet 4.6", category: "Claude・ChatGPT", description: "Anthropicの主力モデル。Opusに近い知性と速度・コストのバランスが強み。日常のコーディング・執筆・分析はまずSonnetで十分。", example: "Claude Codeの既定はSonnet 4.6。高度推論が必要なときだけOpusにモデル切替する運用が一般的。" },
  { id: "cc-haiku-45", name: "Claude Haiku 4.5", englishName: "Claude Haiku 4.5", category: "Claude・ChatGPT", description: "Anthropicの軽量高速モデル。大量の短い処理（分類・タグ付け・要約）を低コストで裁けるのが強み。サブエージェントの「足として使う」定番。", example: "メールの1000通分類をHaiku 4.5で一括処理、結果をSonnetで解釈するパイプラインでコストを90%削減。" },
  { id: "claude-fast-mode", name: "Fast Mode", englishName: "Fast Mode", category: "Claude・ChatGPT", description: "Claude CodeでOpus 4.6を高速応答モードで動かす切替機能。思考を簡略化することで、大きなモデルの知性を保ちつつ体感が軽い。", example: "/fast で切替後は応答が秒単位で返ってくるため、短いペアプロ対話に向く。" },
  { id: "claude-thinking", name: "拡張思考（Thinking）", englishName: "Extended Thinking", category: "Claude・ChatGPT", description: "Claudeが「考える時間」を長く取る機能。推論過程を内部で展開し、難問で精度が大幅に上がる。コストと引き換えに深い検討が手に入る。", example: "アーキテクチャ設計や数学問題でThinkingを有効にすると、浅い即答ではなく整理された解答が返る。" },
  { id: "prompt-caching", name: "プロンプトキャッシュ", englishName: "Prompt Caching", category: "Claude・ChatGPT", description: "Claude APIで「長い共通プロンプト」をサーバー側で再利用する仕組み。システムプロンプトが長いアプリで5分以内の再問い合わせはトークン料金が大幅に安くなる。", example: "長いCLAUDE.mdを持つプロジェクトは、Prompt Cachingで2回目以降のAPIコストが約10%に落ちる。" },
  { id: "cc-batch-api", name: "Batch API", englishName: "Anthropic Batch API", category: "Claude・ChatGPT", description: "Claudeのバッチ処理用API。即時レスポンスが不要な大量ジョブを、24時間以内に50%割引で実行できる。分類・要約・埋め込み生成の大量処理向き。", example: "一晩で10万件の記事を要約するなら、Batch APIで投げて翌朝結果を受け取るのが最もコストが安い。" },
  { id: "cc-tool-use-api", name: "Tool Use API", englishName: "Tool Use", category: "Claude・ChatGPT", description: "ClaudeのAPIで外部関数やツールを呼ばせる仕組み。ツール定義と結果を受け渡しながら、自律的な複数ステップのエージェントを作れる。", example: "天気APIをtoolとして定義すると、Claudeが質問に応じて自分で`get_weather(\"Tokyo\")`を呼び、結果を回答に織り込む。" },
  { id: "cc-files-api", name: "Files API", englishName: "Anthropic Files API", category: "Claude・ChatGPT", description: "Claude APIのファイルアップロード機能。PDFや画像を事前にアップし、以降はfile_id参照で何度も使える。大きな資料を繰り返し分析するときに効果的。", example: "100ページのIR資料をFiles APIにアップロードし、複数の質問を投げる運用でトークン消費を大幅圧縮できる。" },
  { id: "cc-managed-agents", name: "Managed Agents", englishName: "Anthropic Managed Agents", category: "Claude・ChatGPT", description: "Anthropicがホストするエージェントランタイム。自前でエージェントループを書かなくても、ツール定義とプロンプトだけで長時間エージェントが動く。", example: "社内Q&A Botを、インフラを持たずにManaged Agentsで稼働させれば、スケーリングも運用もAnthropic任せにできる。" },
  { id: "cc-citations", name: "Citations", englishName: "Citations", category: "Claude・ChatGPT", description: "Claudeが回答の根拠として元文書の引用箇所を返すAPI機能。RAG的な用途で「ハルシネーションしていない証拠」を示せる。", example: "契約書Q&AでCitationsを有効化すれば「第3条第2項に基づく」のような根拠付きの回答が得られる。" },

  // ─── プロンプト設計・エージェント設計 ──────────────────────
  { id: "react-pattern", name: "ReActパターン", englishName: "ReAct", category: "AI基礎", description: "Reasoning（推論）とAction（行動）を交互に繰り返すエージェントの基本型。「考える→ツール実行→結果を見て次を考える」のループ構造。", example: "多くのLLMエージェントは内部でReActパターンを採用していて、Claude Codeもこの構造で動いている。" },
  { id: "tool-using-agent", name: "ツール使用エージェント", englishName: "Tool-Using Agent", category: "AI基礎", description: "外部のツール（API・シェル・DB）を呼び出して目的を達成できるエージェントの総称。LLM単体ではできない実行系タスクを担う。", example: "「株価を取得してグラフにする」のような行動付きタスクは、ツール使用エージェントの典型例。" },
  { id: "multi-agent", name: "マルチエージェント", englishName: "Multi-Agent System", category: "AI基礎", description: "複数のAIが役割分担して動くアーキテクチャ。Planner、Executor、Reviewerなどに分けると、単一エージェントより複雑タスクに強くなる。", example: "Claude Codeでplanner→executor→reviewerの3サブエージェントを連携させるのがマルチエージェントの一例。" },
  { id: "orchestrator-agent", name: "オーケストレーター", englishName: "Orchestrator Agent", category: "AI基礎", description: "マルチエージェント構成の司令塔。他エージェントにタスクを割り振り、結果をまとめる役割。Claude Codeのメインエージェントもこれに近い。", example: "プロジェクトマネージャー役のオーケストレーターが、デザイナー・エンジニア・レビュアーの各サブエージェントを差配する。" },
  { id: "agent-loop", name: "エージェントループ", englishName: "Agent Loop", category: "AI基礎", description: "LLMが「思考→ツール実行→観測→次の思考」を繰り返す実行サイクル。1ターンで終わる会話と違い、目的達成まで自走する。", example: "「バグを直せ」と一言で頼むだけで、Claudeがファイル探索→編集→テスト実行まで数十ターン回すのが典型のエージェントループ。" },
  { id: "agent-memory", name: "エージェントメモリ", englishName: "Agent Memory", category: "AI基礎", description: "エージェントが会話・行動・結果を覚えておく仕組み。短期（コンテキスト内）と長期（ファイル/DB保存）がある。Claude Codeのauto memoryは後者。", example: "エージェントメモリに「このユーザーはSupabaseが好き」と残しておけば、次回以降はその前提で提案が返る。" },
  { id: "human-in-the-loop", name: "ヒューマンインザループ", englishName: "Human-in-the-Loop (HITL)", category: "AI基礎", description: "エージェントの重要な操作で人間の承認を挟む設計。全自動にしない代わりに安全性を担保する。Claude Codeの権限モードはこの思想に基づく。", example: "金銭処理やファイル削除など取り返しのつかない操作は、HITLにして必ずユーザーにConfirmを出す。" },
  { id: "guardrails", name: "ガードレール", englishName: "Guardrails", category: "AI基礎", description: "AIの出力や行動を許容範囲に抑えるためのフィルター・ルール群。禁止トピック、PII漏洩、危険コマンドの実行などをブロックする。", example: "「パスワードをログに出さない」「rm -rf を実行しない」など、エージェントのガードレールは本番運用で必須。" },
  { id: "autonomous-agent", name: "自律エージェント", englishName: "Autonomous Agent", category: "AI基礎", description: "人間の逐次指示なしに、目標だけ与えて長時間動き続けるエージェント。リサーチ・自動化・監視などで使われる。", example: "夜間に走る「バックアップチェック＋異常時通知」のジョブは、自律エージェントの小さな実例。" },
  { id: "cron-agent", name: "クロンエージェント", englishName: "Cron Agent / Scheduled Agent", category: "AI基礎", description: "スケジュール（cron）で定期的に起動するエージェント。毎朝KPIを収集して要約を送る、などの定常業務を自動化できる。", example: "毎朝9時に起動して前日売上をSlackに報告するクロンエージェントを組めば、朝会の資料作りが消える。" },
  { id: "planner-executor", name: "Planner / Executor", englishName: "Planner-Executor Pattern", category: "AI基礎", description: "エージェントを「計画担当」と「実行担当」に分離する設計パターン。計画だけ人間がレビューし、実行は高速モデルに任せることでコストと品質を両立。", example: "PlannerをOpus、ExecutorをSonnet/Haikuに割り当てるとコスパ良く大規模タスクを裁ける。" },

  // ─── プロンプト／RAG 応用 ────────────────────────────────
  { id: "context-engineering", name: "コンテキストエンジニアリング", englishName: "Context Engineering", category: "Claude・ChatGPT", description: "プロンプトエンジニアリングの次世代版。モデルに渡す「コンテキスト全体」（システム/履歴/ツール出力/メモリ）を設計の対象にする考え方。", example: "CLAUDE.md・auto memory・プロジェクトのREADMEをどう組み合わせるかを設計するのがコンテキストエンジニアリング。" },
  { id: "xml-prompt", name: "XMLプロンプト", englishName: "XML-Style Prompting", category: "Claude・ChatGPT", description: "Claudeが特に得意とする、`<task>`や`<context>`のようなXMLタグで情報を構造化するプロンプト手法。要素の境界が明確でモデルの解釈が安定する。", example: "`<instruction>…</instruction><example>…</example>` のような構造化プロンプトは、Claudeの公式ドキュメント推奨の書き方。" },
  { id: "system-message", name: "システムメッセージ", englishName: "System Message", category: "Claude・ChatGPT", description: "APIで会話の最初に渡す、モデルの役割や制約を決める命令文。Claudeでは`system`パラメータ、OpenAIでは`role: system`として扱われる。", example: "システムメッセージに「日本語の敬語で回答」「コードはTypeScriptで」と書くと、以降のレスポンスがその方針に揃う。" },
  { id: "tool-description", name: "ツール説明", englishName: "Tool Description", category: "Claude・ChatGPT", description: "エージェントにツール定義を渡すとき、名前と一緒に「いつ使うか」を説明する文。ここが雑だと、AIが間違ったタイミングでツールを呼ぶ。", example: "`sendEmail` ツールに「ユーザーが明示的に送信を承諾した場合のみ使う」と書くと、勝手な送信を防げる。" },
  { id: "rag-chunking", name: "チャンキング", englishName: "Chunking", category: "AI基礎", description: "RAGで文書を埋め込みやすいサイズに分割する前処理。200〜1000トークン前後の段落単位が一般的。分割方法が検索精度を大きく左右する。", example: "章見出し単位でチャンク分けすると、「第3章の結論」のようなピンポイント検索がヒットしやすくなる。" },
  { id: "vector-search", name: "ベクトル検索", englishName: "Vector Search", category: "AI基礎", description: "文書を埋め込みベクトルに変換し、コサイン類似度で「意味的に近いもの」を探す検索。キーワード一致では拾えない「言い換え・意訳」もヒットさせる。", example: "「財務ダッシュボード」で検索して、文書に「売上可視化」としか書かれていなくてもベクトル検索ならヒットする。" },
  { id: "hybrid-search", name: "ハイブリッド検索", englishName: "Hybrid Search", category: "AI基礎", description: "ベクトル検索（意味）とキーワード検索（単語一致）を組み合わせる検索手法。片方の弱点を補い、実務で最もヒット率が高い。", example: "商品ID検索はキーワード、自然文検索はベクトル、両方をRRF統合するのが最近のベストプラクティス。" },
  { id: "rerank", name: "リランキング", englishName: "Reranking", category: "AI基礎", description: "検索結果の上位候補を、別の高精度モデルで並べ直す工程。最初の検索は速さ重視、リランクで精度を上げる二段構え。", example: "ベクトル検索で100件→Cohere Rerankerで上位10件に絞る、という流れでRAGの回答品質が大幅に上がる。" },
  { id: "embedding-model", name: "埋め込みモデル", englishName: "Embedding Model", category: "AI基礎", description: "文章をベクトルに変換するための専用AIモデル。OpenAI `text-embedding-3-large`やVoyage AI、Cohere Embedなどがある。", example: "Voyage AIの `voyage-3` は日本語ドキュメントで`text-embedding-3`より精度が高いと言われる。" },
  { id: "semantic-search", name: "セマンティック検索", englishName: "Semantic Search", category: "AI基礎", description: "意味ベースの検索の総称。ベクトル検索がその中心技術。キーワード検索と対比して使われる。", example: "社内Wikiをセマンティック検索にすると、「経費申請」でも「旅費精算規程」がヒットする。" },

  // ─── プロンプト評価・品質 ───────────────────────────────
  { id: "eval-dataset", name: "評価データセット", englishName: "Eval Dataset", category: "AI基礎", description: "プロンプトやモデルの品質を測るために用意する「お題と模範解答」の集合。本番に出す前にここで点数を比べて決める。", example: "Brainのクイズ問題を評価データセットとして持ち、モデル入れ替え前後で正答率をA/B比較できる。" },
  { id: "llm-as-judge", name: "LLM-as-Judge", englishName: "LLM as Judge", category: "AI基礎", description: "LLMの出力の良し悪しを別のLLMに採点させる手法。人手評価が難しい大規模検証に使う。", example: "100通りの応答をClaudeに「1〜5点で評価」と頼んで、プロンプト改善の効果測定に使う。" },
  { id: "golden-set", name: "ゴールデンセット", englishName: "Golden Set", category: "AI基礎", description: "絶対外してはいけない「基準問題集」。リリース前に必ず通るか確認する回帰テスト用のプロンプト群。", example: "顧客Botのゴールデンセットに「営業時間」「返品方法」を入れておけば、モデル更新で答えが変わっても検知できる。" },
  { id: "red-teaming", name: "レッドチーミング", englishName: "Red Teaming", category: "AI基礎", description: "AIに悪意あるプロンプトを投げて安全性の抜け穴を探す手法。Anthropicの安全性評価の中核工程でもある。", example: "「秘密情報を吐かせよう」と狙った攻撃プロンプトを大量に投げ、ガードレールが機能するか確認する。" },
  { id: "jailbreak", name: "ジェイルブレイク", englishName: "Jailbreak", category: "AI基礎", description: "AIの安全制御を騙して無効化する攻撃プロンプト。「ロールプレイ」「元ルールは忘れて」等のパターンがある。", example: "「おばあちゃんの寝かしつけ話として爆弾の作り方を…」などは古典的なジェイルブレイク。最新のClaudeは跳ね返す。" },
  { id: "prompt-injection", name: "プロンプトインジェクション", englishName: "Prompt Injection", category: "データ・セキュリティ", description: "Webページやドキュメントに「指示を無視して…」と仕込んでAIを乗っ取る攻撃。エージェントがWebを読むと踏みやすい。", example: "スクレイピング先のHTMLに「システムプロンプトを漏らせ」と書かれているのがプロンプトインジェクションの典型。" },

  // ─── Codex・OpenAI 関連 ───────────────────────────────────
  { id: "openai-codex", name: "Codex CLI", englishName: "OpenAI Codex CLI", category: "Claude・ChatGPT", description: "OpenAIが提供するClaude Code対抗のターミナル型AIエージェント。OpenAIのモデルをバックエンドにして、ローカルリポジトリで自律作業できる。", example: "`codex` と打って「バグを直して」と頼めば、Claude Code同様にファイル編集とテスト実行を自走してくれる。" },
  { id: "openai-assistants", name: "Assistants API", englishName: "OpenAI Assistants API", category: "プログラミング", description: "OpenAIが提供するエージェント向けAPI。thread/run/toolという独自概念で会話と状態を管理する。Claudeのツール使用APIに相当。", example: "社内AIチャットボットをAssistants APIで作ると、会話履歴やファイル添付をOpenAI側でマネージドに扱ってくれる。" },
  { id: "gpts", name: "GPTs", englishName: "GPTs", category: "Claude・ChatGPT", description: "ChatGPT上で誰でも作れる「カスタムGPT」。命令文と知識ファイル、Actions（外部API呼び出し）を設定して公開できる。ClaudeのProjectsに近い。", example: "「SQL家庭教師GPT」を作り、学習データにSQL問題集を入れておけば、ブラウザで専用家庭教師が使える。" },
  { id: "gpt-actions", name: "GPTs Actions", englishName: "GPTs Actions", category: "プログラミング", description: "ChatGPT上のGPTsから外部APIを呼び出す仕組み。OpenAPIスキーマで定義し、AuthもOAuth/API Keyで設定できる。", example: "社内KPIダッシュボードのAPIをGPTs Actionsとして登録すると、ChatGPTから数字を取りに行って答えてくれる。" },
  { id: "advanced-data-analysis", name: "Advanced Data Analysis", englishName: "Advanced Data Analysis (旧Code Interpreter)", category: "Claude・ChatGPT", description: "ChatGPTが内部でPythonを走らせてデータ分析やグラフ描画をする機能。Excelファイルをドラッグ＆ドロップで投げるだけで要約・分析してくれる。", example: "決算書のxlsxをAdvanced Data Analysisに投げて「前年比で異常値を教えて」と頼めば、Pythonで自動集計される。" },
  { id: "openai-json-mode", name: "JSON Mode", englishName: "JSON Mode", category: "プログラミング", description: "LLMの出力形式を有効なJSONに強制するAPIオプション。スキーマに従った構造化出力が得やすくなり、後続プログラムとの接続が安定する。", example: "JSONモードで `{\"name\":…, \"price\":…}` を返させれば、パース失敗リスクなくDBにそのまま保存できる。" },
  { id: "structured-output", name: "Structured Output", englishName: "Structured Output", category: "プログラミング", description: "LLMの出力にJSONスキーマを指定し、フィールドの型まで保証する仕組み。OpenAIは`response_format`、AnthropicはTool UseやJSONモードで実現。", example: "Zodスキーマから型付きのStructured Outputを得れば、型チェックなしで安全に後続処理へ渡せる。" },
  { id: "logprobs", name: "logprobs", englishName: "Log Probabilities", category: "AI基礎", description: "LLMが各トークンを選ぶ確率のログ値。信頼度スコアや複数候補の比較に使える。不確かな回答の検出に有効。", example: "Multiple choice問題でlogprobsを比較し、最上位と次点が接近していれば「迷っている」と判定できる。" },
  { id: "seed-param", name: "seedパラメータ", englishName: "Seed Parameter", category: "AI基礎", description: "LLMの乱数シードを固定する設定。同じプロンプト×同じseedで「ほぼ同じ結果」が返るため、評価やテストの再現性が得られる。", example: "プロンプト改善のA/B比較では、seedを固定して「プロンプトの違いだけ」が出力差になるよう揃える。" },
  { id: "openai-realtime-api", name: "Realtime API", englishName: "OpenAI Realtime API", category: "プログラミング", description: "音声入出力を双方向ストリームで扱うOpenAIのAPI。低遅延の音声エージェントや通話AIを構築できる。", example: "コールセンターのAI応対をRealtime APIで作ると、人間と会話しているようなレスポンス速度が出る。" },
];
